name: rcaweb
favicon: null
layout_spectrum: 0.87816
typography_spectrum: 0.50318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#669999'
    - '#333333'
    - '#c5c6c8'
    - '#4c7171'
  brandStrength: 1
  lightness: 0.24790312303230166
  saturation: 0.9068181847687811
  rhythmicContrast: 0.2918487952556461
purpose: []
