name: rcaweb
favicon: null
layout_spectrum: 0.15649845893494785
typography_spectrum: 0.8313685853499919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.48242173972539604
  lightness: 0.24790312303230166
  saturation: 0.9068181847687811
  rhythmicContrast: 0.2918487952556461
purpose: []
